<?php

declare(strict_types=1);

namespace Aurora\Core\Content;

/**
 * The value guards every layout normaliser needs.
 *
 * Extracted when the content grid arrived: it lays out on the same 48-column
 * grid as the post banner, with the same responsive spans and the same
 * whitelists on colours and links. Two copies of a guard is two places for one
 * of them to be loosened, and these are the guards that stop a `style`
 * attribute or an `href` from becoming an injection point.
 *
 * Guards only. What a banner or a grid is made of belongs to their own
 * normalisers; this knows what a colour is.
 */
final readonly class ContentValueNormalizer
{
    /**
     * Full width of the layout grid.
     *
     * 48 is not arbitrary: it is 4 × 12 and 2 × 24, so a twelfth is 4 columns
     * and a twenty-fourth is 2. Halves, thirds, quarters, sixths and eighths
     * all land on whole numbers.
     */
    public const int COLUMNS = 48;

    /** Smallest first — an absent step inherits the one below it. */
    public const array BREAKPOINTS = ['base', 'md', 'lg'];

    /**
     * Schemes a link may use. `javascript:` and `data:` are the reason this is
     * a whitelist rather than a blocklist — the value lands in an `href`, and
     * an author is not the only one who can reach these fields.
     */
    private const array URL_PREFIXES = ['/', '#', 'http://', 'https://', 'mailto:', 'tel:'];

    private const string HEX_COLOR = '/^#[0-9a-fA-F]{6}$/';

    /**
     * Ids are generated by the editor, so they arrive from the client and are
     * checked like anything else. Long enough for a uuid, restricted to what
     * is safe as an array key and readable in a payload.
     */
    private const string ITEM_ID = '/^[A-Za-z0-9_-]{1,36}$/';

    /** @param list<string> $allowed */
    public function oneOf(mixed $value, array $allowed, string $fallback): string
    {
        return is_string($value) && in_array($value, $allowed, true) ? $value : $fallback;
    }

    /**
     * Rejects anything that is not a six-digit hex. Renderers drop these
     * straight into a `style` attribute, so a loose value here is an injection
     * point rather than a cosmetic problem.
     */
    public function color(mixed $value): ?string
    {
        return is_string($value) && 1 === preg_match(self::HEX_COLOR, $value) ? mb_strtolower($value) : null;
    }

    /** A link is kept only if it starts with something known-safe. */
    public function url(mixed $value): ?string
    {
        $url = $this->text($value);

        if ('' === $url) {
            return null;
        }

        foreach (self::URL_PREFIXES as $prefix) {
            if (str_starts_with(mb_strtolower($url), $prefix)) {
                return $url;
            }
        }

        return null;
    }

    public function id(mixed $value): ?int
    {
        return is_numeric($value) && (int) $value > 0 ? (int) $value : null;
    }

    public function text(mixed $value): string
    {
        return is_string($value) ? mb_trim($value) : '';
    }

    /**
     * Widths per breakpoint, smallest first. An absent step inherits the one
     * below it — which is why only `base` is guaranteed: an item that says
     * nothing is full width on a phone and stays full width until something
     * says otherwise.
     *
     * @param mixed $raw whatever the client sent
     *
     * @return array<string, int|null>
     */
    public function span(mixed $raw): array
    {
        $data = is_array($raw) ? $raw : [];
        $span = [];

        foreach (self::BREAKPOINTS as $breakpoint) {
            $value = $data[$breakpoint] ?? null;
            $span[$breakpoint] = is_numeric($value)
                ? max(1, min(self::COLUMNS, (int) $value))
                : null;
        }

        $span['base'] ??= self::COLUMNS;

        return $span;
    }

    /**
     * Keeps the editor's id when it is usable and unique, and assigns one
     * otherwise. Generated rather than rejected: an item with no id is still
     * an item an author placed, and dropping it to punish the payload would
     * lose work. Collisions resolve the same way — the second claimant gets a
     * fresh id, so two items can never share a translation's content.
     *
     * @param array<string, bool> $used
     */
    public function itemId(mixed $value, array $used): string
    {
        if (is_string($value) && 1 === preg_match(self::ITEM_ID, $value) && !isset($used[$value])) {
            return $value;
        }

        $next = 1;
        while (isset($used['i'.$next])) {
            ++$next;
        }

        return 'i'.$next;
    }

    /**
     * Widths as CSS custom properties, read by the `.aurora-grid` rule. An
     * absent breakpoint emits nothing, which is what makes it inherit the one
     * below through the variable's own fallback chain.
     *
     * A span is a number chosen at runtime, so it cannot be a class: Tailwind
     * only emits classes it can read in the source.
     *
     * @param array<string, int|null> $span
     */
    public function spanStyle(array $span): string
    {
        $declarations = [];

        foreach ($span as $breakpoint => $columns) {
            if (null !== $columns) {
                $declarations[] = sprintf('--span-%s: %d;', $breakpoint, $columns);
            }
        }

        return implode(' ', $declarations);
    }
}
