<?php

declare(strict_types=1);

namespace Aurora\Module\Configuration\Theme\Service;

use Aurora\Module\Configuration\Theme\Entity\ThemeInterface;
use Aurora\Module\Configuration\Theme\Repository\ThemeRepository;
use Aurora\Module\Ged\Document\Repository\DocumentRepository;
use Aurora\Module\Ged\Document\Service\DocumentUrlGenerator;

final class ThemeContext
{
    /** Default primary colour seed when the active theme has none configured. */
    public const string DEFAULT_PRIMARY_COLOR = '#6366f1';

    private ?ThemeInterface $cachedTheme = null;

    private bool $resolved = false;

    /** @var list<string> */
    public const array CONTENT_WIDTHS = ['narrow', 'wide', 'full'];

    public function __construct(
        private readonly ThemeRepository $themeRepository,
        private readonly DocumentRepository $documentRepository,
        private readonly PrimaryColorPalette $primaryColorPalette,
        private readonly DocumentUrlGenerator $documentUrlGenerator,
    ) {}

    public function activeTheme(): ?ThemeInterface
    {
        if (!$this->resolved) {
            $this->cachedTheme = $this->themeRepository->findActive();
            $this->resolved = true;
        }

        return $this->cachedTheme;
    }

    public function activeThemeSlug(): string
    {
        return $this->activeTheme()?->getSlug() ?? 'default';
    }

    public function headerLogoUrl(): ?string
    {
        $rawId = $this->activeTheme()?->getConfig()['header_logo_media_id'] ?? '';
        if (!is_string($rawId) || '' === $rawId) {
            return null;
        }

        $document = $this->documentRepository->find((int) $rawId);

        return $this->documentUrlGenerator->publicUrl($document);
    }

    public function headerCustomText(): ?string
    {
        $text = $this->activeTheme()?->getConfig()['header_custom_text'] ?? '';

        return (is_string($text) && '' !== $text) ? $text : null;
    }

    public function footerText(string $siteName): string
    {
        $custom = $this->activeTheme()?->getConfig()['footer_text'] ?? '';
        $text = (is_string($custom) && '' !== $custom) ? $custom : '© {year} {siteName}';

        return str_replace(['{year}', '{siteName}'], [date('Y'), $siteName], $text);
    }

    /** Active theme's primary colour as hex (falls back to DEFAULT_PRIMARY_COLOR). */
    /**
     * How wide the frontend content column should be.
     *
     * A theme decides its own chrome, but the reading width is the kind of
     * thing an editor wants to change without touching templates — Notion's
     * "full width" toggle is the reference. Stored per theme rather than
     * globally: switching themes should not carry the previous one's layout.
     *
     * @return 'narrow'|'wide'|'full'
     */
    public function contentWidth(): string
    {
        $value = $this->activeTheme()?->getConfig()['content_width'] ?? '';

        return in_array($value, self::CONTENT_WIDTHS, true) ? $value : 'narrow';
    }

    /**
     * The utility classes for {@see contentWidth()}, so every template does not
     * repeat the mapping and drift from it.
     *
     * These class names live in PHP, which Tailwind does not scan — they are
     * kept generated by an `@source inline(…)` in app.css. Adding a width here
     * means adding it there too, or it renders unstyled.
     */
    public function contentWidthClass(): string
    {
        return match ($this->contentWidth()) {
            'wide' => 'max-w-5xl mx-auto',
            'full' => 'max-w-none',
            default => 'max-w-3xl mx-auto',
        };
    }

    public function primaryColor(): string
    {
        $value = $this->activeTheme()?->getConfig()['primary_color'] ?? '';

        return is_string($value) && '' !== $value ? $value : self::DEFAULT_PRIMARY_COLOR;
    }

    /**
     * Generates the CSS that overrides the --th-accent-* scale from the active theme's
     * primary colour. Output goes inside a <style> in the layout head. Tailwind utilities
     * like bg-accent-600 emit `var(--color-accent-600)` which itself forwards to
     * `var(--th-accent-600)` — overriding --th-accent-* at runtime cascades to every
     * accent-coloured element in the app.
     */
    public function primaryColorCss(): string
    {
        $palette = $this->primaryColorPalette->generate($this->primaryColor());
        $declarations = [];
        foreach ($palette as $stop => $value) {
            $declarations[] = sprintf('--th-accent-%s: %s;', $stop, $value);
        }

        return ':root{'.implode('', $declarations).'}';
    }

    public function cssVariableOverrides(): string
    {
        $config = $this->activeTheme()?->getConfig() ?? [];
        if ([] === $config) {
            return '';
        }

        $parts = [];
        foreach ($config as $key => $value) {
            if (is_string($value) && str_starts_with($key, '--')) {
                $parts[] = $key.': '.$value.';';
            }
        }

        return implode(' ', $parts);
    }
}
