<?php

declare(strict_types=1);

namespace Aurora\Module\Configuration\Theme\Service;

use Aurora\Module\Configuration\Theme\Entity\ThemeInterface;
use Aurora\Module\Configuration\Theme\Enum\ThemeFontEnum;
use Aurora\Module\Configuration\Theme\Repository\ThemeRepository;
use Aurora\Module\Ged\Document\Repository\DocumentRepository;
use Aurora\Module\Ged\Document\Service\DocumentUrlGenerator;

final class ThemeContext
{
    /**
     * Default primary colour seed when the active theme has none configured.
     *
     * Emerald. The palette generator pins each stop's lightness, so the hue can
     * move without dragging contrast with it: white on `accent-600` measures
     * 5.52:1 here against 6.76:1 for the indigo it replaces - both above the
     * 4.5:1 a button label needs.
     */
    public const string DEFAULT_PRIMARY_COLOR = '#10b981';

    private ?ThemeInterface $cachedTheme = null;

    private bool $resolved = false;

    /** @var list<string> */
    public const array CONTENT_WIDTHS = ['narrow', 'wide', 'full'];

    public const array HIGHLIGHTS = ['accent', 'neutral', 'custom'];

    private const string HEX_COLOR = '/^#[0-9a-fA-F]{6}$/';

    public function __construct(
        private readonly ThemeRepository $themeRepository,
        private readonly DocumentRepository $documentRepository,
        private readonly PrimaryColorPalette $primaryColorPalette,
        private readonly SurfaceContrast $surfaceContrast,
        private readonly DocumentUrlGenerator $documentUrlGenerator,
    ) {}

    public function activeTheme(): ?ThemeInterface
    {
        if (!$this->resolved) {
            $this->cachedTheme = $this->themeRepository->findActive();
            $this->resolved = true;
        }

        return $this->cachedTheme;
    }

    public function activeThemeSlug(): string
    {
        return $this->activeTheme()?->getSlug() ?? 'default';
    }

    public function headerLogoUrl(): ?string
    {
        $rawId = $this->activeTheme()?->getConfig()['header_logo_media_id'] ?? '';
        if (!is_string($rawId) || '' === $rawId) {
            return null;
        }

        $document = $this->documentRepository->find((int) $rawId);

        return $this->documentUrlGenerator->publicUrl($document);
    }

    public function headerCustomText(): ?string
    {
        $text = $this->activeTheme()?->getConfig()['header_custom_text'] ?? '';

        return (is_string($text) && '' !== $text) ? $text : null;
    }

    public function footerText(string $siteName): string
    {
        $custom = $this->activeTheme()?->getConfig()['footer_text'] ?? '';
        $text = (is_string($custom) && '' !== $custom) ? $custom : '© {year} {siteName}';

        return str_replace(['{year}', '{siteName}'], [date('Y'), $siteName], $text);
    }

    /** Active theme's primary colour as hex (falls back to DEFAULT_PRIMARY_COLOR). */
    /**
     * How wide the frontend content column should be.
     *
     * A theme decides its own chrome, but the reading width is the kind of
     * thing an editor wants to change without touching templates - Notion's
     * "full width" toggle is the reference. Stored per theme rather than
     * globally: switching themes should not carry the previous one's layout.
     *
     * @return 'narrow'|'wide'|'full'
     */
    public function contentWidth(): string
    {
        $value = $this->activeTheme()?->getConfig()['content_width'] ?? '';

        return in_array($value, self::CONTENT_WIDTHS, true) ? $value : 'narrow';
    }

    /**
     * The utility classes for {@see contentWidth()}, so every template does not
     * repeat the mapping and drift from it.
     *
     * These class names live in PHP, which Tailwind does not scan - they are
     * kept generated by an `@source inline(…)` in app.css. Adding a width here
     * means adding it there too, or it renders unstyled.
     */
    public function contentWidthClass(): string
    {
        return match ($this->contentWidth()) {
            'wide' => 'max-w-5xl mx-auto',
            'full' => 'max-w-none',
            default => 'max-w-3xl mx-auto',
        };
    }

    /**
     * La famille choisie par le thème actif.
     *
     * Rangée dans le thème plutôt que dans un réglage global, pour la même
     * raison que la largeur de contenu : changer de thème doit emporter sa
     * typographie, pas hériter de celle du précédent.
     */
    public function font(): ThemeFontEnum
    {
        return ThemeFontEnum::fromConfig($this->activeTheme()?->getConfig()['font_family'] ?? null);
    }

    /**
     * La règle qui compose l'application dans la police du thème, posée dans le
     * `<head>` par `primary_color_style.html.twig`.
     *
     * Elle redéfinit `--th-font-sans`, dont `--font-sans` n'est qu'un renvoi :
     * `body` s'en sert directement et l'utilitaire `font-sans` en recopie le
     * `var(...)`, donc toute la page suit. Un thème resté sur Poppins n'émet
     * rien : le défaut vit déjà dans `theme.css`, et une règle qui répète un
     * défaut est une seconde copie à tenir à jour.
     */
    public function fontFamilyCss(): string
    {
        $font = $this->font();

        if (ThemeFontEnum::default() === $font) {
            return '';
        }

        return ':root{--th-font-sans: '.$font->stack().';}';
    }

    /**
     * Ce que prennent les survols du site public et les repères des cartes
     * (catégorie, flèche) : la couleur principale, ou le texte de la surface
     * sur laquelle ils sont posés. Le neutre sert aux pages qui jouent déjà
     * leurs propres couleurs et qu'un survol vert viendrait contredire. Le
     * personnalisé sans couleur exploitable retombe sur l'accent.
     *
     * @return 'accent'|'neutral'|'custom'
     */
    public function highlight(): string
    {
        return $this->colorMode('highlight', 'highlight_color');
    }

    public function highlightColor(): ?string
    {
        return $this->hexSetting('highlight_color');
    }

    /**
     * Le choix d'une publication, borné à son contenu comme son accent.
     *
     * Posé sur le conteneur **et** chacun de ses descendants, sous
     * `html[data-theme]` : le mode neutre du thème se pose élément par élément,
     * et seule une règle plus spécifique au même niveau le remplace. `initial`
     * efface la valeur du thème, et le repli sur l'accent reprend la main.
     */
    public function postHighlightCss(string $selector, ?string $highlight, ?string $color): string
    {
        $value = match ($highlight) {
            'accent' => 'initial',
            'neutral' => 'var(--th-primary)',
            'custom' => null !== $color && 1 === preg_match(self::HEX_COLOR, $color) ? $color : null,
            default => null,
        };

        if (null === $value) {
            return '';
        }

        $scope = 'html[data-theme] '.$selector;

        return $scope.','.$scope.' *{--th-highlight: '.$value.';}';
    }

    public function highlightCss(): string
    {
        $color = 'custom' === $this->highlight() ? $this->highlightColor() : null;

        return null !== $color ? 'html[data-theme]{--th-highlight: '.$color.';}' : '';
    }

    /**
     * The mark under the active entry of the top bar: the primary colour,
     * the text colour of the bar, or a colour of its own. Same three modes
     * as the hovers, and the same fallback when a custom colour is missing.
     *
     * @return 'accent'|'neutral'|'custom'
     */
    public function menuActive(): string
    {
        return $this->colorMode('menu_active', 'menu_active_color');
    }

    public function menuActiveColor(): ?string
    {
        return $this->hexSetting('menu_active_color');
    }

    public function menuActiveCss(): string
    {
        $color = 'custom' === $this->menuActive() ? $this->menuActiveColor() : null;

        return null !== $color ? 'html[data-theme]{--th-menu-active: '.$color.';}' : '';
    }

    /**
     * A mode among self::HIGHLIGHTS read from the theme, falling back to the
     * accent - including for `custom` without a usable colour, which would
     * otherwise draw in no colour at all.
     *
     * @return 'accent'|'neutral'|'custom'
     */
    private function colorMode(string $key, string $colorKey): string
    {
        $value = $this->activeTheme()?->getConfig()[$key] ?? '';

        if ('custom' === $value) {
            return null !== $this->hexSetting($colorKey) ? 'custom' : 'accent';
        }

        return in_array($value, self::HIGHLIGHTS, true) ? $value : 'accent';
    }

    /**
     * Strict hex and nothing else: the value lands in a `<style>`, and the
     * theme's configuration is not validated anywhere on the way in.
     */
    private function hexSetting(string $key): ?string
    {
        $value = $this->activeTheme()?->getConfig()[$key] ?? null;

        return is_string($value) && 1 === preg_match(self::HEX_COLOR, $value) ? $value : null;
    }

    public function primaryColor(): string
    {
        $value = $this->activeTheme()?->getConfig()['primary_color'] ?? '';

        return is_string($value) && '' !== $value ? $value : self::DEFAULT_PRIMARY_COLOR;
    }

    /**
     * Generates the CSS that overrides the --th-accent-* scale from the active theme's
     * primary colour. Output goes inside a <style> in the layout head. Tailwind utilities
     * like bg-accent-600 emit `var(--color-accent-600)` which itself forwards to
     * `var(--th-accent-600)` - overriding --th-accent-* at runtime cascades to every
     * accent-coloured element in the app.
     */
    public function primaryColorCss(): string
    {
        $palette = $this->primaryColorPalette->generate($this->primaryColor());
        $declarations = [];
        foreach ($palette as $stop => $value) {
            $declarations[] = sprintf('--th-accent-%s: %s;', $stop, $value);
        }

        return ':root{'.implode('', $declarations).'}';
    }

    /**
     * A publication's own accent, under a selector scoped to its own content
     * rather than `:root` - so choosing ocre for the photography page never
     * touches the topbar or the footer, which stay the theme's.
     *
     * Empty when the post sets nothing: the theme's own `:root` rule, always
     * present, is then the whole answer, exactly as before this existed.
     */
    public function postAccentCss(string $selector, ?string $accentColor): string
    {
        if (null === $accentColor || '' === mb_trim($accentColor)) {
            return '';
        }

        $palette = $this->primaryColorPalette->generate($accentColor);
        $declarations = [];
        foreach ($palette as $stop => $value) {
            $declarations[] = sprintf('--th-accent-%s: %s;', $stop, $value);
        }

        // --th-accent est résolu une fois sur :root et hérité tel quel : sans
        // le reposer ici, `text-accent` et `bg-accent` gardaient la couleur du
        // thème au milieu d'une page qui en avait choisi une autre.
        $declarations[] = '--th-accent: var(--th-accent-500);--th-accent-hover: var(--th-accent-600);';

        return $selector.'{'.implode('', $declarations).'}'
            .'.dark '.$selector.'{--th-accent: var(--th-accent-400);--th-accent-hover: var(--th-accent-500);}';
    }

    public function cssVariableOverrides(): string
    {
        $config = $this->activeTheme()?->getConfig() ?? [];
        if ([] === $config) {
            return '';
        }

        // Filtré à la lecture, faute de l'être à l'écriture : un nom de
        // propriété personnalisée, et une valeur qui ne peut ni fermer la
        // déclaration, ni la règle, ni la balise `<style>` qui la porte.
        $parts = [];
        foreach ($config as $key => $value) {
            if (is_string($value)
                && 1 === preg_match('/^--[A-Za-z0-9_-]+$/', (string) $key)
                && 0 === preg_match('/[;{}<>\\\\]|\/\*/', $value)) {
                $parts[] = $key.': '.$value.';';
            }
        }

        return implode(' ', $parts);
    }

    /**
     * Clés de `Theme::config` portant les couleurs des trois surfaces publiques,
     * associées au sélecteur qu'elles habillent.
     */
    private const array SURFACES = [
        'background_color' => 'html[data-theme]',
        'header_color' => 'html[data-theme] .aurora-surface-header',
        'footer_color' => 'html[data-theme] .aurora-surface-footer',
    ];

    /**
     * Le CSS qui colore le frontend public à partir des couleurs choisies dans
     * l'écran de thème.
     *
     * Une surface non configurée n'émet aucune règle : l'apparence historique
     * (fond clair, texte sombre, topbar et pied transparents) est donc le
     * comportement par défaut, sans valeur à maintenir quelque part.
     *
     * Chaque règle pose le fond **et** le jeu de jetons contrasté qui va avec,
     * au même endroit. Les propriétés personnalisées étant héritées, tout ce que
     * la surface contient suit : libellés, mentions discrètes, bordures, et les
     * panneaux de menu déroulant, peints en `bg-bg`, qui se retrouvent ainsi sur
     * le fond de leur topbar plutôt que sur celui de la page.
     *
     * `$overrides` porte les couleurs de la page en cours de rendu, quand elle
     * en a - une publication peut habiller ses trois surfaces pour elle seule.
     * La substitution se fait surface par surface, et pas en bloc : une
     * publication qui ne choisit que sa topbar garde le fond et le pied du
     * thème, ce qui est le seul sens qui rende `null` utilisable comme
     * « hérite ». Celles d'une publication sont validées à l'écriture
     * (`PostInputFactory::colorOrNull`), mais pas celles du thème, dont la
     * config n'est contrôlée nulle part en entrée : le filtre hexadécimal de
     * `surfaceColor()` est donc la seule garde avant le `<style>` public.
     *
     * @param array<string, string|null> $overrides couleurs par clé de surface, cf. self::SURFACES
     */
    public function frontendSurfacesCss(array $overrides = []): string
    {
        $config = $this->activeTheme()?->getConfig() ?? [];
        $rules = [];

        foreach (self::SURFACES as $key => $selector) {
            // Le vide vaut l'absence des deux côtés, et pas seulement `null` :
            // sans ça une chaîne vide passerait le `??` et éteindrait la
            // couleur du thème au lieu de la laisser passer.
            $color = $this->surfaceColor($overrides[$key] ?? null)
                ?? $this->surfaceColor($config[$key] ?? null);

            if (null === $color) {
                continue;
            }

            $rules[] = $this->surfaceRule($selector, $color);
        }

        return implode('', $rules);
    }

    /**
     * The page's own background rule, under a selector the caller chooses
     * instead of `html[data-theme]`.
     *
     * Written for the banner preview in the post editor: that preview is a
     * Twig fragment injected into the backend's own DOM, which never carries
     * `html[data-theme]` - so a title with no colour of its own rendered in
     * whatever the backend's light or dark mode happened to be, not the one
     * the public page actually shows. Scoped to a class the preview's own
     * wrapper carries, so it never leaks onto the rest of the admin screen.
     *
     * Empty when the theme sets no page background - the preview then falls
     * back to the backend's own colours, which is what an unconfigured public
     * page does too.
     */
    public function previewSurfaceCss(string $selector): string
    {
        $color = $this->surfaceColor($this->activeTheme()?->getConfig()['background_color'] ?? null);

        return null !== $color ? $this->surfaceRule($selector, $color) : '';
    }

    private function surfaceRule(string $selector, string $color): string
    {
        $declarations = ['--th-surface-bg: '.$color.';', '--th-bg: '.$color.';'];
        foreach ($this->surfaceContrast->tokensFor($color) as $token => $value) {
            $declarations[] = $token.': '.$value.';';
        }

        return $selector.'{'.implode('', $declarations).'}';
    }

    /**
     * Une couleur de surface utilisable, ou null.
     *
     * Hexadécimal strict, comme les couleurs de survol : la valeur finit dans
     * un `<style>` servi à tous les visiteurs, et une chaîne libre y fermerait
     * la règle pour écrire la suite de la page.
     */
    private function surfaceColor(mixed $raw): ?string
    {
        if (!is_string($raw)) {
            return null;
        }

        $color = mb_trim($raw);

        return 1 === preg_match(self::HEX_COLOR, $color) ? $color : null;
    }
}
