<?php

declare(strict_types=1);

namespace {{NAMESPACE}}\Setting;

use Aurora\Module\Configuration\Setting\Enum\ApplicationParameterEnumInterface;

/**
 * Module-specific settings for {{MODULE_LABEL}}. Edit this enum to declare
 * your own configurable parameters. Each case becomes a row in
 * `core_settings` (synchronised by `bin/console aurora:application-parameter`)
 * and a field in the admin Settings tab generated by
 * {@see {{MODULE}}ConfigurationTabProvider}.
 */
enum {{MODULE}}SettingEnum: string implements ApplicationParameterEnumInterface
{
    // Example case - replace with your own.
    case ExampleFlag = '{{MODULE_ID}}_example_flag';

    public function getKey(): string
    {
        return $this->value;
    }

    public function getType(): string
    {
        return match ($this) {
            self::ExampleFlag => 'boolean',
        };
    }

    public function getDefaultValue(): string
    {
        return match ($this) {
            self::ExampleFlag => '0',
        };
    }

    public function getLabel(): string
    {
        return match ($this) {
            self::ExampleFlag => 'backend.{{MODULE_ID}}.settings.example_flag',
        };
    }

    public function getDescription(): string
    {
        return match ($this) {
            self::ExampleFlag => 'backend.{{MODULE_ID}}.settings.example_flag_description',
        };
    }

    public function getGroup(): string
    {
        return '{{MODULE_ID}}';
    }

    /**
     * Sample value shown inside the input on the Settings page. Return a
     * translation key for cases where an example is genuinely clearer
     * than the description (e.g. a prefix like `'INV-2026-000042'`, an
     * email like `'admin@example.com'`). Return null for the rest.
     */
    public function getPlaceholder(): ?string
    {
        return match ($this) {
            self::ExampleFlag => null,
        };
    }
}
